datadog:
  apiKeyExistingSecret: datadog-secret
  site: datadoghq.com
  clusterName: my-sandbox-cluster
  kubelet:
    tlsVerify: false
clusterAgent:
  enabled: true
  # token: "abcdabcdabcdabcdabcdabcdabcdabcd"